# Site settings
title: CodeCatz tutorial
repository: https://github.com/CodeCatz/codecatz-tutorial
description: >
  A super beginner-friendly workshop for kittens, 
  who want to build their online CV and blog and
  learn about HTML, CSS and other fun technologies
  for building awesome web sites.
baseurl: "/codecatz-tutorial" # the subpath of your site, e.g. /blog/
url: "http://codecatz.org/codecatz-tutorial" # the base hostname & protocol for your site
twitter_username: CodeCatz
github_username:  CodeCatz

# Build settings
markdown: kramdown
