# Site settings
title: CodeCatz tutorial
email: your-email@domain.com
description: >
  A super beginner-friendly workshop for kittens, 
  who want to build their online CV and blog and
  learn about HTML, CSS and other fun technologies
  for building awesome web sites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codecatz.org" # the base hostname & protocol for your site
twitter_username: CodeCatz
github_username:  codecatz

# Build settings
markdown: kramdown
